In [1]:
import torch
import torch.nn as nn

In [2]:
torch.manual_seed(42)

inputs = torch.tensor([1.0,2.0,3.0])


In [3]:
neuron = nn.Linear(in_features=3,out_features=1)
output = neuron(inputs)

In [4]:
output

tensor([1.5244], grad_fn=<ViewBackward0>)

In [5]:
neuron.weight

Parameter containing:
tensor([[ 0.4414,  0.4792, -0.1353]], requires_grad=True)

In [7]:
neuron.bias

Parameter containing:
tensor([0.5304], requires_grad=True)

In [13]:
# to verify
#neuron.weight @ input + neuron.bias